### ISSUE TITLE
Load pretrained weight from CLIP or LLAVA

### ISSUE THREAD

**Issue by hongsamvo** [AviSoori1x/seemore#2]
Thank you for sharing your work. I just read your code that I don't  find the part that load pretrained weight from CLIP or Llava. May I misunderstand that your work is training from scratch?

**Comment by hongsamvo** [comment]
Thank you. I find out that this work is training from scratch. Can you suggest the dataset that work fine with this baseline? As my understand, you are using mock dataset.

**Comment by AviSoori1x** [comment]
Hey just reading this, I would recommend generating using some of the scripts given here: https://github.com/AviSoori1x/multimodal_LLMs. You can control the image size programmatically as well. Let me know if this works.

**Comment by hongsamvo** [comment]
Thank you for your suggestion!
